# Generated by Django 5.2.1 on 2025-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdata',
            name='fuel_level',
        ),
        migrations.AddField(
            model_name='busdata',
            name='bus_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
