# Generated by Django 5.2.1 on 2025-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0002_remove_busdata_fuel_level_busdata_bus_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdata',
            name='fuel_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
