# Generated by Django 5.2.1 on 2025-12-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0003_busdata_fuel_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdata',
            name='fuel_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
