# Generated by Django 5.2.1 on 2025-12-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0004_busdata_fuel_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busdata',
            old_name='fuel_distance',
            new_name='fuel_percent',
        ),
    ]
